### ISSUE TITLE
Missing test coverage

### ISSUE THREAD

**Issue by mih** [adswa/multimatch#26]
Overall coverage is nice already, there is just one largeish conditional that is not covered, yet. Should ideally be added to make further refactoring more reliable. (sorry no link yet)

**Comment by adswa** [comment]
Thanks for noticing. Desperate attempts at testing revealed that piece of code is dead -- the conditional never gets fulfilled. I've double checked the Matlab code, and its been dead in there as well. So for now, I've just commented this code out. This way, functionality/results are exactly as original toolbox, but that comes at the expense of never simplifying any last saccadic event, even if it fulfills the conditions to be simplified...
